[package]
name = "itm-decode"
version = "0.1.5"
authors = [
        "Viktor Sonesten <v@tmplt.dev>",
]
edition = "2018"
readme = "README.md"
repository = "https://github.com/tmplt/itm-decode"
license = "MIT OR Apache-2.0"
description = "A sans-I/O library for decoding ITM and DWT packets"
homepage = "https://github.com/tmplt/itm-decode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmatch = "0.1.1"
bitvec = "0.19.4"
funty = "=1.1.0"
anyhow = "1.0"

[lib]
name = "itm_decode"

[[bin]]
name = "itm-decode"
