[package]
authors = [
    "The Cortex-M Team <cortex-m@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
description = "Tool to parse and dump ITM packets"
documentation = "https://docs.rs/itm"
edition = "2018"
keywords = ["parse", "ARM", "ITM"]
license = "MIT OR Apache-2.0"
name = "itm"
repository = "https://github.com/japaric/itm"
version = "0.4.0"

[dependencies]
byteorder = "1.3.0"
failure = "0.1.5"
failure_derive = "0.1.5"
either = "1.5.0"
