[package]
authors = [
    "The Cortex-M Team <cortex-m@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
build = "build.rs"
description = "Tool to parse and dump ITM packets"
documentation = "https://docs.rs/itm"
keywords = ["parse", "tool", "ARM", "ITM"]
license = "MIT OR Apache-2.0"
name = "itm"
repository = "https://github.com/japaric/itm"
version = "0.3.1"

[dependencies]
chrono = "^0.4"
clap = "^2.14.0"
env_logger = "^0.4.3"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "^0.3.8"

[dev-dependencies]
tempdir = "0.3.5"
