[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "Tool to parse and dump ITM packets"
documentation = "https://docs.rs/itm"
keywords = ["parse", "tool", "ARM", "ITM"]
license = "MIT OR Apache-2.0"
name = "itm"
repository = "https://github.com/japaric/itm"
version = "0.1.0"

[dependencies]
clap = "2.14.0"
error-chain = "0.5.0"
libc = "0.2.17"
ref_slice = "1.1.0"
