[package]
name = "itm-decode"
version = "0.1.0"
authors = [
        "Viktor Sonesten <v@tmplt.dev>",
]
edition = "2018"
readme = "README.org"
repository = "https://github.com/tmplt/itm-decode"
license = "MIT OR Apache-2.0"
description = "A sans-I/O library for decoding ITM and DWT packets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmatch = "0.1.1"
